name: fabric mod build and release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Change gradlew permissions
      run: chmod +x ./gradlew
      
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Build with Gradle
      run: ./gradlew buildMatrix
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-build
        path: output/*
        
    - name: Set environment variables
      run: |
        echo "TAG_NAME=v$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        echo "RELEASE_TITLE=Build $(date +'%Y%m%d %H:%M:%S')" >> $GITHUB_ENV
        echo "BUILD_DATE_UTC=$(date -u '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "BUILD_DATE_BJ=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        
    - name: Create Tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag ${{ env.TAG_NAME }}
        git push origin ${{ env.TAG_NAME }}
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: ${{ env.RELEASE_TITLE }}
        body: |
          自动构建发布
          - 构建时间（UTC）：${{ env.BUILD_DATE_UTC }}
          - 构建时间（北京时间）：${{ env.BUILD_DATE_BJ }}
          - 提交哈希：`${{ github.sha }}`
        draft: false
        files: output/*
